const WORDS = [
  { en: "apple", ko: "사과" },
  { en: "book", ko: "책" },
  { en: "computer", ko: "컴퓨터" },
  { en: "dog", ko: "개" },
  { en: "elephant", ko: "코끼리" },
  { en: "friend", ko: "친구" },
  { en: "garden", ko: "정원" },
  { en: "house", ko: "집" },
  { en: "island", ko: "섬" },
  { en: "journey", ko: "여행" },
  { en: "kitchen", ko: "주방" },
  { en: "library", ko: "도서관" },
  { en: "mountain", ko: "산" },
  { en: "notebook", ko: "공책" },
  { en: "ocean", ko: "바다" },
  { en: "pencil", ko: "연필" },
  { en: "question", ko: "질문" },
  { en: "river", ko: "강" },
  { en: "school", ko: "학교" },
  { en: "teacher", ko: "선생님" },
  { en: "umbrella", ko: "우산" },
  { en: "village", ko: "마을" },
  { en: "window", ko: "창문" },
  { en: "year", ko: "년" },
  { en: "zebra", ko: "얼룩말" },
];
